name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: '2690' 
          proxy_host: ${{ secrets.JUMP_HOST }}
          proxy_username: ${{ secrets.JUMP_USER }}
          proxy_key: ${{ secrets.PRIVATE_KEY }}  # Use the same key for the proxy
          script: |
            echo "SSH connection successful!"

      - name: Execute Deployment Script on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: '2690'
          proxy_host: ${{ secrets.JUMP_HOST }}
          proxy_username: ${{ secrets.JUMP_USER }}
          proxy_key: ${{ secrets.PRIVATE_KEY }}
          script: |
            /opt/deployment-scripts/deploy.sh \
              https://github.com/${{ github.repository }} \
              ${{ github.ref_name }}